version: '3.8'

services:
  # -----------------------------
  # 1. Backend API (Golang Engine)
  # -----------------------------
  backend:
    container_name: hunt-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=hunter
      - DB_PASSWORD=secretpassword
      - DB_NAME=huntdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROBE_BATCH_SIZE=1000
      - TRUSTED_RESOLVERS=1.1.1.1,8.8.8.8,1.0.0.1,8.8.4.4
      # تنظیمات تلگرام (مقادیر خودت را جایگزین کردی که عالیه)
      - TELEGRAM_BOT_TOKEN=8186397853:AAGbnh2A5AnGgju9qobtL5joh9G8SSEYGV8
      - TELEGRAM_CHAT_ID=-1003320492297
    volumes:
      # 👇 این خط برای وردلیست‌های سفارشی اضافه شد (برای آینده)
      - ./custom_wordlists:/wordlists/custom
    depends_on:
      - postgres
      - redis
    networks:
      - hunt-net
    restart: unless-stopped

  # -----------------------------
  # 2. Frontend Dashboard (React/Modern UI)
  # -----------------------------
  # 👇👇👇 این بخش از کامنت خارج شد
  frontend:
    container_name: hunt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80" # داشبورد روی پورت 3000 در دسترس خواهد بود
    depends_on:
      - backend
    networks:
      - hunt-net
    restart: unless-stopped

  # -----------------------------
  # 3. Databases & Cache
  # -----------------------------
  postgres:
    container_name: hunt-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hunter
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: huntdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hunt-net
    restart: unless-stopped

  redis:
    container_name: hunt-redis
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - hunt-net
    restart: unless-stopped

# Networks & Volumes
networks:
  hunt-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data: