package handlers

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/omidxplimbo/hunt-engine/backend/internal/api/dto"
	"github.com/omidxplimbo/hunt-engine/backend/internal/platform/featureflags"
	"github.com/omidxplimbo/hunt-engine/backend/internal/worker/phases/security/nuclei"
)

var nucleiDraftTagPattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9_-]{0,31}$`)

// GetNucleiTemplateDraftStatus reports whether draft generation is enabled.
func GetNucleiTemplateDraftStatus(c *fiber.Ctx) error {
	cfg := nuclei.LoadConfig()
	provider := "disabled"
	if cfg.AllowAITemplates {
		provider = "local-draft"
	}

	return c.JSON(fiber.Map{
		"status": "success",
		"data": dto.NucleiTemplateDraftStatusResponse{
			Enabled:             cfg.AllowAITemplates,
			Provider:            provider,
			DraftOnly:           true,
			RequiresHumanReview: true,
			SaveAutomatically:   false,
		},
	})
}

// GenerateNucleiTemplateDraft creates a constrained Nuclei YAML draft.
// It is intentionally disabled by default and never writes to /data/nuclei/custom.
func GenerateNucleiTemplateDraft(c *fiber.Ctx) error {
	_, ownerKey, _, _, ownerErr := currentAccountOwner(c)
	if ownerErr != nil {
		return ownerErr
	}
	if !featureflags.IsEnabledForOwner(ownerKey, featureflags.KeyAINucleiTemplateDrafts) {
		return featureflags.DisabledResponse(c, featureflags.KeyAINucleiTemplateDrafts)
	}

	cfg := nuclei.LoadConfig()
	if !cfg.AllowAITemplates {
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"status":  "error",
			"message": "AI-assisted Nuclei template drafts are disabled. Set NUCLEI_ALLOW_AI_TEMPLATES=true to enable draft-only generation.",
		})
	}

	req := new(dto.GenerateNucleiTemplateDraftRequest)
	if err := c.BodyParser(req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"status": "error", "message": "Invalid request body", "error": err.Error()})
	}

	content, name, err := buildNucleiTemplateDraft(req)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"status": "error", "message": err.Error()})
	}

	resp := dto.NucleiTemplateDraftResponse{
		Name:                name,
		Content:             content,
		DraftOnly:           true,
		RequiresHumanReview: true,
		Saved:               false,
	}

	if req.Validate {
		validation := runNucleiTemplateValidation(name, content)
		resp.Validation = &validation
	}

	return c.JSON(fiber.Map{"status": "success", "data": resp})
}

func buildNucleiTemplateDraft(req *dto.GenerateNucleiTemplateDraftRequest) (string, string, error) {
	name, err := validateNucleiTemplateName(req.Name)
	if err != nil {
		return "", "", err
	}

	templateID := strings.TrimSuffix(strings.TrimSuffix(name, ".yaml"), ".yml")
	title := strings.TrimSpace(req.Title)
	if title == "" {
		title = templateID
	}

	description := strings.TrimSpace(req.Description)
	if description == "" {
		description = "Draft-only Nuclei template generated by Hunt Engine. Review and validate before use."
	}

	severity := normalizeDraftSeverity(req.Severity)
	if severity == "" {
		return "", "", fmt.Errorf("severity must be one of info, low, medium, high, critical")
	}

	method := normalizeDraftMethod(req.Method)
	if method == "" {
		return "", "", fmt.Errorf("method must be one of GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS")
	}

	path := strings.TrimSpace(req.Path)
	if path == "" {
		path = "/"
	}
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}

	matcherType := strings.ToLower(strings.TrimSpace(req.MatcherType))
	if matcherType == "" {
		matcherType = "word"
	}
	matcherPart := strings.ToLower(strings.TrimSpace(req.MatcherPart))
	if matcherPart == "" {
		matcherPart = "body"
	}
	matcherValue := strings.TrimSpace(req.MatcherValue)
	if matcherValue == "" {
		return "", "", fmt.Errorf("matcher_value is required")
	}

	tags := normalizeDraftTags(req.Tags)
	if len(tags) == 0 {
		tags = []string{"custom", "draft"}
	}

	matcherYAML, err := draftMatcherYAML(matcherType, matcherPart, matcherValue)
	if err != nil {
		return "", "", err
	}

	content := fmt.Sprintf(`id: %s

info:
  name: %s
  author: hunt-engine
  severity: %s
  description: %s
  tags: %s
  metadata:
    hunt_engine_draft: "true"
    requires_human_review: "true"

http:
  - method: %s
    path:
      - "{{BaseURL}}%s"

    matchers:
%s
`, templateID, yamlQuote(title), severity, yamlQuote(description), strings.Join(tags, ","), method, yamlEscapePath(path), matcherYAML)

	return content, name, nil
}

func normalizeDraftSeverity(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "":
		return "info"
	case "info", "low", "medium", "high", "critical":
		return strings.ToLower(strings.TrimSpace(value))
	default:
		return ""
	}
}

func normalizeDraftMethod(value string) string {
	v := strings.ToUpper(strings.TrimSpace(value))
	if v == "" {
		return "GET"
	}
	switch v {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
		return v
	default:
		return ""
	}
}

func normalizeDraftTags(values []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(values))

	for _, value := range values {
		for _, part := range strings.Split(value, ",") {
			tag := strings.ToLower(strings.TrimSpace(part))
			if tag == "" || !nucleiDraftTagPattern.MatchString(tag) {
				continue
			}
			if _, ok := seen[tag]; ok {
				continue
			}
			seen[tag] = struct{}{}
			out = append(out, tag)
		}
	}

	return out
}

func draftMatcherYAML(matcherType, matcherPart, matcherValue string) (string, error) {
	switch matcherType {
	case "word":
		return fmt.Sprintf("      - type: word\n        part: %s\n        words:\n          - %s", sanitizeMatcherPart(matcherPart), yamlQuote(matcherValue)), nil
	case "regex":
		return fmt.Sprintf("      - type: regex\n        part: %s\n        regex:\n          - %s", sanitizeMatcherPart(matcherPart), yamlQuote(matcherValue)), nil
	case "status":
		statusCode, err := strconv.Atoi(strings.TrimSpace(matcherValue))
		if err != nil || statusCode < 100 || statusCode > 599 {
			return "", fmt.Errorf("status matcher_value must be an HTTP status code between 100 and 599")
		}
		return fmt.Sprintf("      - type: status\n        status:\n          - %d", statusCode), nil
	default:
		return "", fmt.Errorf("matcher_type must be one of word, regex, status")
	}
}

func sanitizeMatcherPart(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "header", "headers":
		return "header"
	case "raw", "all":
		return "raw"
	case "body", "":
		return "body"
	default:
		return "body"
	}
}

func yamlQuote(value string) string {
	return strconv.Quote(strings.TrimSpace(value))
}

func yamlEscapePath(value string) string {
	return strings.ReplaceAll(strings.TrimSpace(value), `"`, `\"`)
}
