package recommendation

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/omidxplimbo/hunt-engine/backend/internal/models"
	"github.com/omidxplimbo/hunt-engine/backend/internal/platform/database"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const (
	SourceSystemDeterministic = "system"

	TypeValidateTakeover        = "validate_takeover"
	TypeValidateJSSecret        = "validate_js_secret"
	TypeReviewExposedVCS        = "review_exposed_vcs"
	TypeReviewExposedConfig     = "review_exposed_config"
	TypeReviewSensitiveService  = "review_sensitive_service"
	TypeReviewNucleiFinding     = "review_nuclei_finding"
	TypeReviewExposedInterface  = "review_exposed_interface"
	TypeInvestigateServerErrors = "investigate_server_errors"
	TypeRunCrawling             = "run_crawling"
	TypeRunNuclei               = "run_nuclei"
	TypeImproveCoverage         = "improve_coverage"
)

type TargetRecommendationInput struct {
	TargetID        uint
	CreatedByUserID *uint
}

type draft struct {
	FindingID          *uint
	RecommendationType string
	Priority           string
	Confidence         string
	Title              string
	Description        string
	Rationale          string
	Evidence           map[string]interface{}
	Action             map[string]interface{}
}

type aggregateCounter struct {
	Count      int
	FindingIDs []uint
	Samples    []string
}

func GenerateTargetRecommendations(input TargetRecommendationInput) ([]models.AIRecommendation, error) {
	if input.TargetID == 0 {
		return nil, fmt.Errorf("target_id is required")
	}

	var target models.Target
	if err := database.DB.First(&target, input.TargetID).Error; err != nil {
		return nil, fmt.Errorf("load target: %w", err)
	}

	analysisID, analysisOutput, err := latestTargetAnalysis(target.ID)
	if err != nil {
		return nil, err
	}

	findings, err := activeFindings(target.ID)
	if err != nil {
		return nil, err
	}

	drafts := buildFindingRecommendations(findings)
	drafts = append(drafts, buildCoverageRecommendations(target, analysisOutput)...)

	if len(drafts) == 0 {
		drafts = append(drafts, draft{
			RecommendationType: TypeImproveCoverage,
			Priority:           "low",
			Confidence:         "medium",
			Title:              "No immediate remediation recommendation generated",
			Description:        "No strong actionable finding was available from the current stored evidence. Continue monitoring and improve scan coverage as needed.",
			Rationale:          "This recommendation is informational. It does not indicate a confirmed vulnerability.",
			Evidence: map[string]interface{}{
				"target_id":   target.ID,
				"root_domain": target.RootDomain,
			},
			Action: map[string]interface{}{
				"steps": []string{
					"Review scan coverage and enabled modules.",
					"Run additional crawling or Nuclei profiles if appropriate.",
					"Manually validate any business-critical exposed assets.",
				},
			},
		})
	}

	rows := make([]models.AIRecommendation, 0, len(drafts))
	now := time.Now().UTC()

	for _, d := range drafts {
		row := models.AIRecommendation{
			TargetID:           target.ID,
			FindingID:          d.FindingID,
			AnalysisID:         analysisID,
			CreatedByUserID:    input.CreatedByUserID,
			Source:             SourceSystemDeterministic,
			RecommendationType: strings.ToLower(strings.TrimSpace(d.RecommendationType)),
			Priority:           normalizePriority(d.Priority),
			Confidence:         normalizeConfidence(d.Confidence),
			Status:             models.AIRecommendationStatusOpen,
			Title:              strings.TrimSpace(d.Title),
			Description:        strings.TrimSpace(d.Description),
			Rationale:          strings.TrimSpace(d.Rationale),
			EvidenceJSON:       jsonb(d.Evidence),
			ActionJSON:         jsonb(d.Action),
		}

		if row.Title == "" {
			row.Title = "Review target security evidence"
		}
		if row.Description == "" {
			row.Description = "Review the stored Hunt Engine evidence and validate whether remediation is required."
		}
		if row.Rationale == "" {
			row.Rationale = "Generated by deterministic Hunt Engine recommendation rules."
		}

		row.CreatedAt = now
		row.UpdatedAt = now
		rows = append(rows, row)
	}

	err = database.DB.Transaction(func(tx *gorm.DB) error {
		// Regenerate only open deterministic recommendations. Accepted/rejected/implemented
		// recommendations are preserved as user decisions.
		if err := tx.
			Where("target_id = ? AND source = ? AND status = ?", target.ID, SourceSystemDeterministic, models.AIRecommendationStatusOpen).
			Delete(&models.AIRecommendation{}).Error; err != nil {
			return err
		}

		if len(rows) == 0 {
			return nil
		}

		return tx.Create(&rows).Error
	})
	if err != nil {
		return nil, fmt.Errorf("save recommendations: %w", err)
	}

	return rows, nil
}

func activeFindings(targetID uint) ([]models.Finding, error) {
	rows := make([]models.Finding, 0)

	err := database.DB.
		Where("target_id = ? AND status NOT IN ?", targetID, []string{
			models.FindingStatusFixed,
			models.FindingStatusFalsePositive,
		}).
		Order(`CASE severity
			WHEN 'critical' THEN 5
			WHEN 'high' THEN 4
			WHEN 'medium' THEN 3
			WHEN 'low' THEN 2
			WHEN 'info' THEN 1
			ELSE 0
		END DESC, last_seen DESC, id DESC`).
		Limit(100).
		Find(&rows).Error

	if err != nil {
		return nil, fmt.Errorf("load active findings: %w", err)
	}

	return rows, nil
}

func latestTargetAnalysis(targetID uint) (*uint, map[string]interface{}, error) {
	var row models.AIAnalysis

	err := database.DB.
		Where("target_id = ? AND scope = ? AND status = ?", targetID, models.AIAnalysisScopeTarget, models.AIAnalysisStatusCompleted).
		Order("created_at DESC, id DESC").
		First(&row).Error

	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, map[string]interface{}{}, nil
		}
		return nil, nil, fmt.Errorf("load latest analysis: %w", err)
	}

	output := map[string]interface{}{}
	if len(row.OutputJSON) > 0 {
		_ = json.Unmarshal(row.OutputJSON, &output)
	}

	id := row.ID
	return &id, output, nil
}

func buildFindingRecommendations(findings []models.Finding) []draft {
	out := make([]draft, 0)

	aggregates := map[string]*aggregateCounter{}

	addAggregate := func(key string, f models.Finding) {
		a := aggregates[key]
		if a == nil {
			a = &aggregateCounter{}
			aggregates[key] = a
		}
		a.Count++
		a.FindingIDs = append(a.FindingIDs, f.ID)
		if len(a.Samples) < 5 {
			a.Samples = append(a.Samples, f.Title)
		}
	}

	for _, f := range findings {
		category := strings.ToLower(strings.TrimSpace(f.Category))
		source := strings.ToLower(strings.TrimSpace(f.SourceTool))
		severity := strings.ToLower(strings.TrimSpace(f.Severity))

		switch {
		case category == "subdomain-takeover":
			out = append(out, findingDraft(
				f,
				TypeValidateTakeover,
				priorityForStrongFinding(severity, "high"),
				"high",
				"Validate possible subdomain takeover",
				"Manually validate the takeover candidate before making customer-facing claims or remediation changes.",
				"Takeover indicators can be high impact when confirmed, but must be verified through provider-specific evidence and safe proof steps.",
				[]string{
					"Confirm the CNAME target and provider ownership state.",
					"Check whether the external service/resource is unclaimed.",
					"Validate safely without taking over customer-owned production traffic.",
					"Remove or correct stale DNS records if confirmed.",
				},
			))

		case category == "js-secret":
			out = append(out, findingDraft(
				f,
				TypeValidateJSSecret,
				priorityForStrongFinding(severity, "high"),
				"medium",
				"Validate possible JavaScript secret exposure",
				"Review the JavaScript evidence and determine whether the detected value is a real credential, token, API key, or harmless identifier.",
				"Secret-like patterns in client-side JavaScript are not automatically confirmed credentials, but they require focused validation.",
				[]string{
					"Inspect the matched value and surrounding code context.",
					"Determine whether the value grants access to a real service.",
					"Rotate exposed credentials if confirmed.",
					"Move sensitive secrets server-side and restrict API scopes.",
				},
			))

		case category == "exposed-vcs":
			out = append(out, findingDraft(
				f,
				TypeReviewExposedVCS,
				priorityForStrongFinding(severity, "high"),
				confidenceForSource(source),
				"Review exposed version control artefact",
				"Validate whether version control paths or files are publicly accessible and whether sensitive repository history can be retrieved.",
				"Exposed VCS artefacts can leak source code, credentials, internal endpoints, and deployment history.",
				[]string{
					"Request the matched URL and adjacent VCS metadata safely.",
					"Confirm whether source or history is accessible.",
					"Block public access to VCS directories at the web server or CDN layer.",
					"Rotate credentials if repository contents were exposed.",
				},
			))

		case category == "exposed-config":
			out = append(out, findingDraft(
				f,
				TypeReviewExposedConfig,
				priorityForStrongFinding(severity, "high"),
				confidenceForSource(source),
				"Review exposed configuration artefact",
				"Validate whether the exposed configuration file contains credentials, internal infrastructure details, or sensitive operational data.",
				"Configuration exposure can become high impact when secrets, internal endpoints, or deployment settings are present.",
				[]string{
					"Review the matched configuration path and response body.",
					"Identify credentials, tokens, database URLs, or internal service names.",
					"Remove the file from public web roots and add deny rules.",
					"Rotate exposed secrets if confirmed.",
				},
			))

		case category == "exposed-service":
			out = append(out, findingDraft(
				f,
				TypeReviewSensitiveService,
				priorityForStrongFinding(severity, "medium"),
				confidenceForSource(source),
				"Validate exposed sensitive service",
				"Confirm whether the exposed service is intentionally internet-facing and protected by strong authentication and network controls.",
				"Public sensitive services increase attack surface and should be reviewed even when no exploit is confirmed.",
				[]string{
					"Identify the service, port, and asset owner.",
					"Verify authentication, authorization, TLS, and network exposure.",
					"Restrict access by VPN, allowlist, or private networking when possible.",
					"Patch or harden the service according to vendor guidance.",
				},
			))

		case source == "nuclei":
			out = append(out, findingDraft(
				f,
				TypeReviewNucleiFinding,
				priorityForStrongFinding(severity, "medium"),
				"medium",
				"Review Nuclei finding evidence",
				"Validate the Nuclei finding using the matched template, host, URL, and structured evidence before reporting or remediation.",
				"Nuclei findings are useful scanner evidence, but commercial reporting still requires validation of exploitability and impact.",
				[]string{
					"Review template ID, matched URL, matcher output, and evidence JSON.",
					"Reproduce the finding manually where safe.",
					"Confirm business impact and affected asset ownership.",
					"Apply the template-specific remediation if confirmed.",
				},
			))

		case category == "exposed-interface":
			addAggregate(TypeReviewExposedInterface, f)

		case category == "server-error":
			addAggregate(TypeInvestigateServerErrors, f)

		default:
			if severity == models.FindingSeverityCritical || severity == models.FindingSeverityHigh {
				out = append(out, findingDraft(
					f,
					TypeReviewNucleiFinding,
					priorityForStrongFinding(severity, "medium"),
					confidenceForSource(source),
					"Review high-priority finding",
					"Validate this high-priority finding and determine whether it represents exploitable risk.",
					"High severity labels should be backed by reproducible evidence before customer-facing reporting.",
					[]string{
						"Review finding evidence and affected asset.",
						"Attempt safe manual reproduction.",
						"Document impact, affected scope, and remediation.",
					},
				))
			}
		}
	}

	if a := aggregates[TypeReviewExposedInterface]; a != nil && a.Count > 0 {
		out = append(out, draft{
			RecommendationType: TypeReviewExposedInterface,
			Priority:           "medium",
			Confidence:         "low",
			Title:              fmt.Sprintf("Validate %d exposed admin/login interface indicators", a.Count),
			Description:        "Review exposed login or administration interface indicators and determine whether they are intended, protected, and monitored.",
			Rationale:          "Admin/login indicators are attack-surface context, not confirmed vulnerabilities. They should not inflate critical risk without access-control weakness or sensitive exposure.",
			Evidence: map[string]interface{}{
				"finding_ids": a.FindingIDs,
				"samples":     a.Samples,
				"count":       a.Count,
				"category":    "exposed-interface",
			},
			Action: map[string]interface{}{
				"steps": []string{
					"Confirm whether each interface is intentionally exposed.",
					"Verify authentication, MFA, rate limiting, lockout, and default credential controls.",
					"Restrict administrative interfaces by VPN, SSO, IP allowlist, or private network where possible.",
					"Prioritize interfaces on live assets with open ports and no CDN/WAF protection.",
				},
			},
		})
	}

	if a := aggregates[TypeInvestigateServerErrors]; a != nil && a.Count > 0 {
		out = append(out, draft{
			RecommendationType: TypeInvestigateServerErrors,
			Priority:           "low",
			Confidence:         "low",
			Title:              fmt.Sprintf("Investigate %d server error indicators", a.Count),
			Description:        "Review repeated server-side error responses for possible instability, debug exposure, or unintended behavior.",
			Rationale:          "5xx responses are operational signals and require validation before being treated as security findings.",
			Evidence: map[string]interface{}{
				"finding_ids": a.FindingIDs,
				"samples":     a.Samples,
				"count":       a.Count,
				"category":    "server-error",
			},
			Action: map[string]interface{}{
				"steps": []string{
					"Re-request affected URLs and compare status codes.",
					"Check whether errors expose stack traces, debug data, or sensitive headers.",
					"Route recurring errors to the owning application team.",
				},
			},
		})
	}

	return out
}

func buildCoverageRecommendations(target models.Target, analysisOutput map[string]interface{}) []draft {
	out := make([]draft, 0)
	seen := map[string]bool{}

	add := func(d draft) {
		if seen[d.RecommendationType] {
			return
		}
		seen[d.RecommendationType] = true
		out = append(out, d)
	}

	gaps := stringList(analysisOutput["coverage_gaps"])
	for _, gap := range gaps {
		lower := strings.ToLower(gap)

		if strings.Contains(lower, "no crawled urls") {
			add(draft{
				RecommendationType: TypeRunCrawling,
				Priority:           "medium",
				Confidence:         "medium",
				Title:              "Improve URL crawling coverage",
				Description:        "Run or re-run crawling and passive URL collection to improve application coverage before relying on findings completeness.",
				Rationale:          "Coverage gaps are not vulnerabilities, but low URL coverage limits confidence in application-layer analysis.",
				Evidence: map[string]interface{}{
					"coverage_gap": gap,
					"target_id":    target.ID,
				},
				Action: map[string]interface{}{
					"steps": []string{
						"Enable or re-run CRAWLING for this target.",
						"Verify Wayback, GAU, Katana, Waymore, and VirusTotal collection status.",
						"Review authentication or scope limitations that may reduce crawling visibility.",
					},
				},
			})
		}

		if strings.Contains(lower, "no javascript") {
			add(draft{
				RecommendationType: TypeImproveCoverage,
				Priority:           "low",
				Confidence:         "medium",
				Title:              "Improve JavaScript intelligence coverage",
				Description:        "Collect and analyze same-root-domain JavaScript resources to improve endpoint, source map, and client-side exposure visibility.",
				Rationale:          "Missing JavaScript coverage can reduce visibility into client-side routes, API endpoints, and source map exposure.",
				Evidence: map[string]interface{}{
					"coverage_gap": gap,
					"target_id":    target.ID,
				},
				Action: map[string]interface{}{
					"steps": []string{
						"Re-run crawling after confirming live web assets.",
						"Check whether JavaScript is served from same-root-domain hosts or third-party CDNs.",
						"Review CSP and asset hosting patterns for coverage limitations.",
					},
				},
			})
		}

		if strings.Contains(lower, "no nuclei") {
			recType := TypeRunNuclei
			title := "Run Nuclei security scanning"
			description := "Enable and run Nuclei using an appropriate commercial-safe profile against live web assets."

			if target.UseNuclei {
				recType = TypeImproveCoverage
				title = "Verify Nuclei scan coverage"
				description = "Nuclei was enabled, but no Nuclei findings are stored. Verify that the scan completed, templates were available, and live assets were in scope."
			}

			add(draft{
				RecommendationType: recType,
				Priority:           "low",
				Confidence:         "medium",
				Title:              title,
				Description:        description,
				Rationale:          "Absence of scanner findings does not prove absence of risk. This is a coverage recommendation, not a vulnerability.",
				Evidence: map[string]interface{}{
					"coverage_gap": gap,
					"target_id":    target.ID,
					"use_nuclei":   target.UseNuclei,
				},
				Action: map[string]interface{}{
					"steps": []string{
						"Confirm Nuclei is enabled for the target.",
						"Use a safe or balanced profile depending on authorization.",
						"Verify template directory and custom templates are synced correctly.",
						"Review worker logs and scan state for Nuclei completion.",
					},
				},
			})
		}
	}

	return out
}

func findingDraft(f models.Finding, recType, priority, confidence, title, description, rationale string, steps []string) draft {
	findingID := f.ID

	return draft{
		FindingID:          &findingID,
		RecommendationType: recType,
		Priority:           priority,
		Confidence:         confidence,
		Title:              title,
		Description:        description,
		Rationale:          rationale,
		Evidence: map[string]interface{}{
			"finding_id":      f.ID,
			"title":           f.Title,
			"severity":        f.Severity,
			"category":        f.Category,
			"source_tool":     f.SourceTool,
			"status":          f.Status,
			"last_seen":       f.LastSeen,
			"evidence_json":   parseJSON(f.EvidenceJSON),
			"legacy_evidence": strings.TrimSpace(f.Evidence),
		},
		Action: map[string]interface{}{
			"steps": steps,
		},
	}
}

func priorityForStrongFinding(severity string, fallback string) string {
	switch strings.ToLower(strings.TrimSpace(severity)) {
	case models.FindingSeverityCritical:
		return "critical"
	case models.FindingSeverityHigh:
		return "high"
	case models.FindingSeverityMedium:
		return "medium"
	case models.FindingSeverityLow:
		return "low"
	default:
		return fallback
	}
}

func confidenceForSource(source string) string {
	switch strings.ToLower(strings.TrimSpace(source)) {
	case "nuclei", "takeover":
		return "high"
	case "js-intel":
		return "medium"
	case "builtin":
		return "low"
	default:
		return "medium"
	}
}

func normalizePriority(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "critical", "high", "medium", "low", "info":
		return strings.ToLower(strings.TrimSpace(value))
	default:
		return "medium"
	}
}

func normalizeConfidence(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "high", "medium", "low":
		return strings.ToLower(strings.TrimSpace(value))
	default:
		return "medium"
	}
}

func jsonb(value interface{}) datatypes.JSON {
	raw, err := json.Marshal(value)
	if err != nil || len(raw) == 0 {
		return datatypes.JSON([]byte("{}"))
	}
	return datatypes.JSON(raw)
}

func parseJSON(raw datatypes.JSON) interface{} {
	text := strings.TrimSpace(string(raw))
	if text == "" {
		return map[string]interface{}{}
	}

	var out interface{}
	if err := json.Unmarshal([]byte(text), &out); err != nil {
		return map[string]interface{}{}
	}
	return out
}

func stringList(value interface{}) []string {
	items, ok := value.([]interface{})
	if !ok {
		return nil
	}

	out := make([]string, 0, len(items))
	for _, item := range items {
		text := strings.TrimSpace(fmt.Sprint(item))
		if text != "" && text != "<nil>" {
			out = append(out, text)
		}
	}
	return out
}
